schema:
  columns:
    - name: id
      data_type:
        type: integer
      generator:
        provider: "number"
        method: "positive"
    - name: first_name
      data_type:
        type: varchar
        max_length: 50
      generator:
        provider: "name"
        method: "firstName"
    - name: last_name
      data_type:
        type: varchar
        max_length: 50
      generator:
        provider: "name"
        method: "lastName"
  constraints:
    - constraint:
        type: primary_key
      columns:
        - id
    - constraint:
        type: unique
      columns:
        - first_name
        - last_name
